### ISSUE TITLE
This is similar to the Chrome

### ISSUE THREAD

**Issue by DDL56x** [unknown-user-account/Blackest-Black-Theme-for-Google-Chrome#1]
and Chromium experimental under chrome://flags...except it doesn't affect a theme being used.

Auto Dark Mode for Web Contents
Automatically render all web contents using a dark theme. – Mac, Windows, Linux, ChromeOS, Android, Fuchsia, Lacros

[#enable-force-dark](chrome://flags/#enable-force-dark)

**Comment by unknown-user-account** [comment]
Yes I know but that isn't an issue so Im closing this.
